TitleFinder/Models/UrlData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TitleFinder.Models
{
    public class UrlData
    {
        public string Title { get; set; }
        public string Url { get; set; }
    }
}

TitleFinder/Controllers/FinderController.cs
using Microsoft.AspNetCore.Mvc;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using TitleFinder.Models;

namespace TitleFinder.Controllers
{
    public class FinderController : Controller
    {
        [HttpPost]
        public async Task<ActionResult<string>> FindAsync(string url)
        {
            var client = new WebClient();
            string source = await client.DownloadStringTaskAsync(url);
            string title = Regex.Match(source, @"\<title\b[^>]*\>\s*(?<Title>[\s\S]*?)\</title\>",
                RegexOptions.IgnoreCase).Groups["Title"].Value;
            return Ok(new UrlData { Url = url, Title = title });
        }
    }
}

TitleFinder/Pages/Finder.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TitleFinder.Models;

namespace TitleFinder.Pages
{
    public class FinderModel : PageModel
    {
        public string[] Urls { get; set; }
        public void OnGet(string[] urls)
        {
            Urls = urls;
        }
    }
}

TitleFinder/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TitleFinder.Models;

namespace TitleFinder.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string Urls { get; set; }
        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            var urls = Urls.Split(Environment.NewLine);
            return RedirectToPage("./Finder", new { urls });
        }
    }
}

TitleFinder/Pages/Finder.cshtml
@page
@model TitleFinder.Pages.FinderModel
@{
}

<table id="urls-table">
    <tr>
        <th>URL</th>
        <th>Title</th>
        <th>Status</th>
    </tr>
    @foreach(var url in Model.Urls)
    {
        <tr id="@url">
            <td>@url</td>
            <td></td>
            <td></td>
        </tr>
    }
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script type="text/javascript">

    window.onload = function () {
        var tables = $('#urls-table');
        for (var i = 1, row; row = tables[0].rows[i]; i++) {
            $.ajax({
                url: '@Url.Action("Find", "Finder")',
                type: 'POST',
                cache: false,
                data: { url: row.cells[0].innerHTML },
                success: function (result, textStatus, xhr) {
                    var row = document.getElementById(result.url)
                    row.innerHTML = "<td>" + result.url + "</td>" +
                                    "<td>" + result.title + "</td>" +
                                    "<td>" + xhr.status + "</td>";
                }
            });
        }
    }
</script>

TitleFinder/Pages/Index.cshtml
@page
@model TitleFinder.Pages.IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<p>Enter URLs:</p>

<form method="post">
    <textarea asp-for="Urls"></textarea>
    <button type="submit">Find Title</button>
</form>